name: shiv nand
favicon: null
layout_spectrum: 0.042333466466516256
typography_spectrum: 0.2375996911432594
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.8423636881634593
  lightness: 0.8423055745661259
  saturation: 0.9082273389212787
  rhythmicContrast: 0.40919019328430295
purpose: []
